name: pcn_erp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^1.0.0
  syncfusion_flutter_pdfviewer: ^18.4.41-beta
  #path_provider: ^1.6.18
  #open_file: ^3.0.1

  webview_flutter_plus: ^0.1.1+10
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.4
  #google_maps_webservice: ^0.0.20-nullsafety.2
  provider: ^4.3.2+2

  firebase_core: "0.5.3"

  theme_provider: ^0.4.0+1

  onesignal_flutter: ^2.0.0
  flutter_native_splash: ^0.2.8
  moor_flutter: ^3.1.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/pcnGlogo.png
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/ajah.jpg
    - assets/mcalogo.png
    - assets/rev_s_okoro.jpeg
    - assets/womenguild.jpg
    - assets/pypan.jpg
    - assets/pcnGlogo.png
    - assets/cgit.jpg
    - assets/moder2.jpeg
    - assets/pcnlogo1.jpg
    - assets/pdf/efik-hymn.pdf
    - assets/pdf/Ajah.pdf
    - assets/pdf/Pnp.pdf
    - assets/pdf/almanc.pdf
    - assets/pdf/bluebook.pdf
    - assets/pdf/BOOK_OF_SERVICE.pdf
    - assets/bible.json
    - assets/pdf/ModEke.pdf
    #- assets/pdf/Practice and Procedure.json
    - assets/igbo/main.css
    - assets/igbo/jquery.mobile-1.4.3.min.js
    - assets/igbo/jquery.mobile-1.4.3.min.css
    - assets/igbo/jquery-2.1.0.min.js
    - assets/igbo/index.html
    - assets/igbo/abu1.html
    - assets/igbo/abu2.html
    - assets/igbo/abu3.html
    - assets/igbo/abu4.html
    - assets/igbo/abu5.html
    - assets/igbo/abu6.html
    - assets/igbo/abu7.html
    - assets/igbo/abu8.html
    - assets/igbo/abu9.html
    - assets/igbo/abu10.html
    - assets/igbo/abu11.html
    - assets/igbo/abu12.html
    - assets/igbo/abu13.html
    - assets/igbo/abu14.html
    - assets/igbo/abu15.html
    - assets/igbo/abu16.html
    - assets/igbo/abu17.html
    - assets/igbo/abu18.html
    - assets/igbo/abu19.html
    #- assets/igbo/abu20.html
    - assets/igbo/abu21.html
    - assets/igbo/abu22.html
    - assets/igbo/abu23.html
    - assets/igbo/abu24.html
    - assets/igbo/abu25.html
    - assets/igbo/abu26.html
    - assets/igbo/abu27.html
    - assets/igbo/abu28.html
    - assets/igbo/abu29.html
    - assets/igbo/abu30.html
    - assets/igbo/abu31.html
    - assets/igbo/abu32.html
    - assets/igbo/abu34.html
    - assets/igbo/abu33.html
    - assets/igbo/abu35.html
    - assets/igbo/abu36.html
    #- assets/igbo/abu37.html
    - assets/igbo/abu38.html
    - assets/igbo/abu39.html
    - assets/igbo/abu40.html
    - assets/igbo/abu41.html
    - assets/igbo/abu42.html
    #- assets/igbo/abu43.html
    - assets/igbo/abu44.html
    - assets/igbo/abu45.html
    #- assets/igbo/abu46.html
    #- assets/igbo/abu47.html
    - assets/igbo/abu48.html
    - assets/igbo/abu49.html
    - assets/igbo/abu50.html
    #- assets/igbo/abu51.html
    - assets/igbo/abu52.html
    - assets/igbo/abu53.html
    - assets/igbo/abu54.html
    - assets/igbo/abu55.html
    - assets/igbo/abu56.html
    - assets/igbo/abu57.html
    - assets/igbo/abu58.html
    - assets/igbo/abu59.html
    - assets/igbo/abu60.html
    - assets/igbo/abu61.html
    #- assets/igbo/abu62.html
    - assets/igbo/abu63.html
    - assets/igbo/abu64.html
    - assets/igbo/abu65.html
    - assets/igbo/abu66.html
    - assets/igbo/abu67.html
    - assets/igbo/abu68.html
    - assets/igbo/abu69.html
    - assets/igbo/abu70.html
    - assets/igbo/abu71.html
    - assets/igbo/abu72.html
    - assets/igbo/abu73.html
    - assets/igbo/abu74.html
    - assets/igbo/abu75.html
    - assets/igbo/abu76.html
    - assets/igbo/abu77.html
    - assets/igbo/abu78.html
    - assets/igbo/abu79.html
    - assets/igbo/abu80.html
    - assets/igbo/abu81.html
    - assets/igbo/abu82.html
    - assets/igbo/abu83.html
    - assets/igbo/abu84.html
    - assets/igbo/abu85.html
    - assets/igbo/abu86.html
    - assets/igbo/abu87.html
    - assets/igbo/abu88.html
    - assets/igbo/abu89.html
    - assets/igbo/abu90.html
    - assets/igbo/abu91.html
    #- assets/igbo/abu92.html
    - assets/igbo/abu93.html
    - assets/igbo/abu94.html
    - assets/igbo/abu95.html
    - assets/igbo/abu96.html
    - assets/igbo/abu97.html
    - assets/igbo/abu98.html
    - assets/igbo/abu99.html
    #- assets/igbo/abu100.html
    - assets/igbo/abu101.html
    - assets/igbo/abu102.html
    - assets/igbo/abu103.html
    #- assets/igbo/abu104.html
    #- assets/igbo/abu105.html
    - assets/igbo/abu106.html
    #- assets/igbo/abu107.html
    #- assets/igbo/abu108.html
    #- assets/igbo/abu109.html
    #- assets/igbo/abu110.html
    - assets/igbo/abu111.html
    - assets/igbo/abu112.html
    #- assets/igbo/abu113.html
    #- assets/igbo/abu114.html
    #- assets/igbo/abu115.html
    - assets/igbo/abu116.html
    - assets/igbo/abu117.html
    #- assets/igbo/abu118.html
    #- assets/igbo/abu119.html
    - assets/igbo/abu120.html
    - assets/igbo/abu121.html
    #- assets/igbo/abu122.html
    #- assets/igbo/abu123.html
    - assets/igbo/abu124.html
    #- assets/igbo/abu125.html
    #- assets/igbo/abu126.html
    - assets/igbo/abu127.html
    #- assets/igbo/abu128.html
    #- assets/igbo/abu129.html
    #- assets/igbo/abu130.html
    - assets/igbo/abu131.html
    - assets/igbo/abu132.html
    #- assets/igbo/abu133.html
    #- assets/igbo/abu134.html
    #- assets/igbo/abu135.html
    #- assets/igbo/abu136.html
    #- assets/igbo/abu137.html
    #- assets/igbo/abu138.html
    - assets/igbo/abu139.html
    - assets/igbo/abu140.html
    - assets/igbo/abu141.html
    - assets/igbo/abu142.html
    - assets/igbo/abu143.html
    #- assets/igbo/abu144.html
    #- assets/igbo/abu145.html
    #- assets/igbo/abu146.html
    #- assets/igbo/abu147.html
    #- assets/igbo/abu148.html
    - assets/igbo/abu149.html
    #- assets/igbo/abu150.html
    #- assets/igbo/abu151.html
    #- assets/igbo/abu152.html
    #- assets/igbo/abu153.html
    - assets/igbo/abu154.html
    - assets/igbo/abu155.html
    #- assets/igbo/abu156.html
    #- assets/igbo/abu157.html
    #- assets/igbo/abu158.html
    #- assets/igbo/abu159.html
    - assets/igbo/abu160.html
    #- assets/igbo/abu161.html
    #- assets/igbo/abu162.html
    - assets/igbo/abu163.html
    #- assets/igbo/abu164.html
    #- assets/igbo/abu165.html
    #- assets/igbo/abu166.html
    #- assets/igbo/abu167.html
    - assets/igbo/abu168.html
    #- assets/igbo/abu169.html
    #- assets/igbo/abu170.html
    #- assets/igbo/abu171.html
    #- assets/igbo/abu172.html
    - assets/igbo/abu173.html
    - assets/igbo/abu174.html
    #- assets/igbo/abu175.html
    #- assets/igbo/abu176.html
    - assets/igbo/abu177.html
    #- assets/igbo/abu178.html
    #- assets/igbo/abu179.html
    #- assets/igbo/abu180.html
    #- assets/igbo/abu181.html
    #- assets/igbo/abu182.html
    #- assets/igbo/abu183.html
    #- assets/igbo/abu184.html
    - assets/igbo/abu185.html
    #- assets/igbo/abu186.html
    #- assets/igbo/abu187.html
    #- assets/igbo/abu189.html
    #- assets/igbo/abu190.html
    - assets/igbo/abu191.html
    - assets/igbo/abu192.html
    - assets/igbo/abu193.html
    #- assets/igbo/abu194.html
    #- assets/igbo/abu195.html
    #- assets/igbo/abu196.html
    - assets/igbo/abu197.html
    - assets/igbo/abu198.html
    #- assets/igbo/abu199.html
    #- assets/igbo/abu200.html
    #- assets/igbo/abu201.html
    #- assets/igbo/abu202.html
    - assets/igbo/abu203.html
    - assets/igbo/abu204.html
    #- assets/igbo/abu205.html
    #- assets/igbo/abu206.html
    #- assets/igbo/abu207.html
    #- assets/igbo/abu208.html
    - assets/igbo/abu209.html
    #- assets/igbo/abu210.html
    #- assets/igbo/abu211.html
    #- assets/igbo/abu212.html
    #- assets/igbo/abu213.html
    - assets/igbo/abu214.html
    #- assets/igbo/abu215.html
    #- assets/igbo/abu216.html
    - assets/igbo/abu217.html
    - assets/igbo/abu218.html
    #- assets/igbo/abu219.html
    #- assets/igbo/abu220.html
    #- assets/igbo/abu221.html
    #- assets/igbo/abu222.html
    #- assets/igbo/abu223.html
    #- assets/igbo/abu224.html
    #- assets/igbo/abu225.html
    - assets/igbo/abu226.html
    - assets/igbo/abu227.html
    #- assets/igbo/abu228.html
    #- assets/igbo/abu229.html
    - assets/igbo/abu230.html
    #- assets/igbo/abu231.html
    #- assets/igbo/abu232.html
    #- assets/igbo/abu233.html
    - assets/igbo/abu234.html
    #- assets/igbo/abu235.html
    #- assets/igbo/abu236.html
    - assets/igbo/abu237.html
    #- assets/igbo/abu238.html
    #- assets/igbo/abu239.html
    - assets/igbo/abu240.html
    #- assets/igbo/abu241.html
    #- assets/igbo/abu242.html
    - assets/igbo/abu243.html
    - assets/igbo/abu244.html
    #- assets/igbo/abu245.html
    #- assets/igbo/abu246.html
    #- assets/igbo/abu247.html
    - assets/igbo/abu248.html
    #- assets/igbo/abu249.html
    #- assets/igbo/abu250.html
    - assets/igbo/abu251.html
    - assets/igbo/abu252.html
    #- assets/igbo/abu253.html
   # - assets/igbo/abu254.html
    #- assets/igbo/abu255.html
    #- assets/igbo/abu256.html
    - assets/igbo/abu257.html
    - assets/igbo/abu258.html
    #- assets/igbo/abu259.html
    #- assets/igbo/abu260.html
    #- assets/igbo/abu261.html
    #- assets/igbo/abu262.html
    - assets/igbo/abu263.html
    #- assets/igbo/abu264.html
    #- assets/igbo/abu265.html
    #- assets/igbo/abu266.html
    - assets/igbo/abu267.html
    #- assets/igbo/abu268.html
    #- assets/igbo/abu269.html
    #- assets/igbo/abu270.html
    #- assets/igbo/abu271.html
    #- assets/igbo/abu272.html
    #- assets/igbo/abu273.html
    #- assets/igbo/abu274.html
    #- assets/igbo/abu275.html
    - assets/igbo/abu276.html
    #- assets/igbo/abu277.html
    #- assets/igbo/abu278.html
    - assets/igbo/abu279.html
    - assets/igbo/abu280.html
    #- assets/igbo/abu281.html
    #- assets/igbo/abu282.html
    - assets/igbo/abu283.html
    - assets/igbo/abu284.html
    #- assets/igbo/abu285.html
    - assets/igbo/abu286.html
    - assets/igbo/abu287.html
    #- assets/igbo/abu288.html
    - assets/igbo/abu289.html
    #- assets/igbo/abu290.html
    - assets/igbo/abu291.html
    - assets/igbo/abu292.html
    #- assets/igbo/abu293.html
    #- assets/igbo/abu294.html
    #- assets/igbo/abu295.html
    - assets/igbo/abu296.html
    - assets/igbo/abu297.html
    - assets/igbo/abu298.html
    #- assets/igbo/abu299.html
    #- assets/igbo/abu300.html
    #- assets/igbo/abu301.html
    - assets/igbo/abu302.html
    #- assets/igbo/abu303.html
    #- assets/igbo/abu304.html
    #- assets/igbo/abu305.html
    - assets/igbo/abu306.html
    #- assets/igbo/abu307.html
    #- assets/igbo/abu308.html
    - assets/igbo/abu309.html
    #- assets/igbo/abu310.html
    #- assets/igbo/abu311.html
    #- assets/igbo/abu312.html
    #- assets/igbo/abu313.html
    #- assets/igbo/abu314.html
    #- assets/igbo/abu315.html
    - assets/igbo/abu316.html
    #- assets/igbo/abu317.html
    #- assets/igbo/abu318.html
    #- assets/igbo/abu319.html
    #- assets/igbo/abu320.html
    #- assets/igbo/abu321.html
    #- assets/igbo/abu322.html
    #- assets/igbo/abu323.html
    #- assets/igbo/abu324.html
    - assets/igbo/abu325.html
    #- assets/igbo/abu326.html
    #- assets/igbo/abu327.html
    #- assets/igbo/abu328.html
    - assets/igbo/abu329.html
    - assets/igbo/abu330.html
    #- assets/igbo/abu331.html
    #- assets/igbo/abu332.html
    #- assets/igbo/abu333.html
    - assets/igbo/abu334.html
    - assets/igbo/abu335.html
    #- assets/igbo/abu336.html
    #- assets/igbo/abu337.html
    #- assets/igbo/abu338.html
    - assets/igbo/abu339.html
    - assets/igbo/abu340.html
    #- assets/igbo/abu341.html
    - assets/igbo/abu342.html
    - assets/igbo/abu343.html
    - assets/igbo/abu344.html
    - assets/igbo/abu345.html
    - assets/igbo/abu346.html
    - assets/igbo/abu347.html
    - assets/igbo/abu348.html
    - assets/igbo/abu349.html
    - assets/igbo/abu350.html
    #- assets/igbo/abu351.html
    - assets/igbo/abu352.html
    - assets/igbo/abu353.html
    - assets/igbo/abu354.html
    - assets/igbo/abu356.html
    - assets/igbo/abu357.html
    - assets/igbo/abu358.html
    - assets/igbo/abu359.html
    - assets/igbo/abu360.html
    - assets/igbo/abu361.html
    - assets/igbo/abu362.html
    - assets/igbo/abu363.html
    - assets/igbo/abu364.html
    - assets/igbo/abu365.html
    - assets/igbo/abu366.html
    - assets/igbo/abu367.html
    #- assets/igbo/abu368.html
    #- assets/igbo/abu369.html
    #- assets/igbo/abu370.html
    - assets/igbo/abu371.html
    - assets/igbo/abu372.html
    #- assets/igbo/abu373.html
    #- assets/igbo/abu374.html
    #- assets/igbo/abu375.html
    #- assets/igbo/abu376.html
    - assets/igbo/abu377.html
    #- assets/igbo/abu378.html
    #- assets/igbo/abu379.html
    #- assets/igbo/abu380.html
    - assets/igbo/abu381.html
    #- assets/igbo/abu382.html
    #- assets/igbo/abu383.html
    #- assets/igbo/abu384.html
    #- assets/igbo/abu385.html
    #- assets/igbo/abu386.html
    #- assets/igbo/abu387.html
    #- assets/igbo/abu388.html
    - assets/igbo/abu389.html
    - assets/igbo/abu390.html
    #- assets/igbo/abu391.html
    - assets/igbo/abu392.html
    #- assets/igbo/abu393.html
    #- assets/igbo/abu394.html
    #- assets/igbo/abu395.html
    #- assets/igbo/abu396.html
    - assets/igbo/abu397.html
    - assets/igbo/abu398.html
    #- assets/igbo/abu399.html
    #- assets/igbo/abu400.html
    #- assets/igbo/abu401.html
    #- assets/igbo/abu402.html
    #- assets/igbo/abu403.html



  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
